-- Taylor Swift discography seed data
-- Albums with Taylor's Version where applicable, vault tracks included

INSERT INTO songs (title, album, album_order, track_number, is_vault) VALUES
-- Taylor Swift (Debut) - album_order 1
('Tim McGraw', 'Taylor Swift', 1, 1, false),
('Picture to Burn', 'Taylor Swift', 1, 2, false),
('Teardrops on My Guitar', 'Taylor Swift', 1, 3, false),
('A Place in This World', 'Taylor Swift', 1, 4, false),
('Cold as You', 'Taylor Swift', 1, 5, false),
('The Outside', 'Taylor Swift', 1, 6, false),
('Tied Together with a Smile', 'Taylor Swift', 1, 7, false),
('Stay Beautiful', 'Taylor Swift', 1, 8, false),
('Should''ve Said No', 'Taylor Swift', 1, 9, false),
('Mary''s Song (Oh My My My)', 'Taylor Swift', 1, 10, false),
('Our Song', 'Taylor Swift', 1, 11, false),

-- Fearless (Taylor's Version) - album_order 2
('Fearless', 'Fearless', 2, 1, false),
('Fifteen', 'Fearless', 2, 2, false),
('Love Story', 'Fearless', 2, 3, false),
('Hey Stephen', 'Fearless', 2, 4, false),
('White Horse', 'Fearless', 2, 5, false),
('You Belong with Me', 'Fearless', 2, 6, false),
('Breathe', 'Fearless', 2, 7, false),
('Tell Me Why', 'Fearless', 2, 8, false),
('You''re Not Sorry', 'Fearless', 2, 9, false),
('The Way I Loved You', 'Fearless', 2, 10, false),
('Forever & Always', 'Fearless', 2, 11, false),
('The Best Day', 'Fearless', 2, 12, false),
('Change', 'Fearless', 2, 13, false),
('Jump Then Fall', 'Fearless', 2, 14, false),
('Untouchable', 'Fearless', 2, 15, false),
('Forever & Always (Piano Version)', 'Fearless', 2, 16, false),
('Come in with the Rain', 'Fearless', 2, 17, false),
('Superstar', 'Fearless', 2, 18, false),
('The Other Side of the Door', 'Fearless', 2, 19, false),
('You All Over Me', 'Fearless (Taylor''s Version)', 2, 20, true),
('Mr. Perfectly Fine', 'Fearless (Taylor''s Version)', 2, 21, true),
('We Were Happy', 'Fearless (Taylor''s Version)', 2, 22, true),
('That''s When', 'Fearless (Taylor''s Version)', 2, 23, true),
('Don''t You', 'Fearless (Taylor''s Version)', 2, 24, true),
('Bye Bye Baby', 'Fearless (Taylor''s Version)', 2, 25, true),

-- Speak Now (Taylor's Version) - album_order 3
('Mine', 'Speak Now', 3, 1, false),
('Sparks Fly', 'Speak Now', 3, 2, false),
('Back to December', 'Speak Now', 3, 3, false),
('Speak Now', 'Speak Now', 3, 4, false),
('Dear John', 'Speak Now', 3, 5, false),
('Mean', 'Speak Now', 3, 6, false),
('The Story of Us', 'Speak Now', 3, 7, false),
('Never Grow Up', 'Speak Now', 3, 8, false),
('Enchanted', 'Speak Now', 3, 9, false),
('Better Than Revenge', 'Speak Now', 3, 10, false),
('Innocent', 'Speak Now', 3, 11, false),
('Haunted', 'Speak Now', 3, 12, false),
('Last Kiss', 'Speak Now', 3, 13, false),
('Long Live', 'Speak Now', 3, 14, false),
('Ours', 'Speak Now', 3, 15, false),
('If This Was a Movie', 'Speak Now', 3, 16, false),
('Superman', 'Speak Now', 3, 17, false),
('Electric Touch', 'Speak Now (Taylor''s Version)', 3, 18, true),
('When Emma Falls in Love', 'Speak Now (Taylor''s Version)', 3, 19, true),
('I Can See You', 'Speak Now (Taylor''s Version)', 3, 20, true),
('Castles Crumbling', 'Speak Now (Taylor''s Version)', 3, 21, true),
('Foolish One', 'Speak Now (Taylor''s Version)', 3, 22, true),
('Timeless', 'Speak Now (Taylor''s Version)', 3, 23, true),

-- Red (Taylor's Version) - album_order 4
('State of Grace', 'Red', 4, 1, false),
('Red', 'Red', 4, 2, false),
('Treacherous', 'Red', 4, 3, false),
('I Knew You Were Trouble', 'Red', 4, 4, false),
('All Too Well', 'Red', 4, 5, false),
('22', 'Red', 4, 6, false),
('I Almost Do', 'Red', 4, 7, false),
('We Are Never Ever Getting Back Together', 'Red', 4, 8, false),
('Stay Stay Stay', 'Red', 4, 9, false),
('The Last Time', 'Red', 4, 10, false),
('Holy Ground', 'Red', 4, 11, false),
('Sad Beautiful Tragic', 'Red', 4, 12, false),
('The Lucky One', 'Red', 4, 13, false),
('Everything Has Changed', 'Red', 4, 14, false),
('Starlight', 'Red', 4, 15, false),
('Begin Again', 'Red', 4, 16, false),
('The Moment I Knew', 'Red', 4, 17, false),
('Come Back... Be Here', 'Red', 4, 18, false),
('Girl at Home', 'Red', 4, 19, false),
('State of Grace (Acoustic)', 'Red (Taylor''s Version)', 4, 20, false),
('Ronan', 'Red (Taylor''s Version)', 4, 21, true),
('Better Man', 'Red (Taylor''s Version)', 4, 22, true),
('Nothing New', 'Red (Taylor''s Version)', 4, 23, true),
('Babe', 'Red (Taylor''s Version)', 4, 24, true),
('Message in a Bottle', 'Red (Taylor''s Version)', 4, 25, true),
('I Bet You Think About Me', 'Red (Taylor''s Version)', 4, 26, true),
('Forever Winter', 'Red (Taylor''s Version)', 4, 27, true),
('Run', 'Red (Taylor''s Version)', 4, 28, true),
('The Very First Night', 'Red (Taylor''s Version)', 4, 29, true),
('All Too Well (10 Minute Version)', 'Red (Taylor''s Version)', 4, 30, true),

-- 1989 (Taylor's Version) - album_order 5
('Welcome to New York', '1989', 5, 1, false),
('Blank Space', '1989', 5, 2, false),
('Style', '1989', 5, 3, false),
('Out of the Woods', '1989', 5, 4, false),
('All You Had to Do Was Stay', '1989', 5, 5, false),
('Shake It Off', '1989', 5, 6, false),
('I Wish You Would', '1989', 5, 7, false),
('Bad Blood', '1989', 5, 8, false),
('Wildest Dreams', '1989', 5, 9, false),
('How You Get the Girl', '1989', 5, 10, false),
('This Love', '1989', 5, 11, false),
('I Know Places', '1989', 5, 12, false),
('Clean', '1989', 5, 13, false),
('Wonderland', '1989', 5, 14, false),
('You Are in Love', '1989', 5, 15, false),
('New Romantics', '1989', 5, 16, false),
('"Slut!"', '1989 (Taylor''s Version)', 5, 17, true),
('Say Don''t Go', '1989 (Taylor''s Version)', 5, 18, true),
('Now That We Don''t Talk', '1989 (Taylor''s Version)', 5, 19, true),
('Suburban Legends', '1989 (Taylor''s Version)', 5, 20, true),
('Is It Over Now?', '1989 (Taylor''s Version)', 5, 21, true),
('Bad Blood [feat. Kendrick Lamar]', '1989 (Taylor''s Version)', 5, 22, false),

-- reputation - album_order 6
('...Ready for It?', 'reputation', 6, 1, false),
('End Game', 'reputation', 6, 2, false),
('I Did Something Bad', 'reputation', 6, 3, false),
('Don''t Blame Me', 'reputation', 6, 4, false),
('Delicate', 'reputation', 6, 5, false),
('Look What You Made Me Do', 'reputation', 6, 6, false),
('So It Goes...', 'reputation', 6, 7, false),
('Gorgeous', 'reputation', 6, 8, false),
('Getaway Car', 'reputation', 6, 9, false),
('King of My Heart', 'reputation', 6, 10, false),
('Dancing with Our Hands Tied', 'reputation', 6, 11, false),
('Dress', 'reputation', 6, 12, false),
('This Is Why We Can''t Have Nice Things', 'reputation', 6, 13, false),
('Call It What You Want', 'reputation', 6, 14, false),
('New Year''s Day', 'reputation', 6, 15, false),

-- Lover - album_order 7
('I Forgot That You Existed', 'Lover', 7, 1, false),
('Cruel Summer', 'Lover', 7, 2, false),
('Lover', 'Lover', 7, 3, false),
('The Man', 'Lover', 7, 4, false),
('The Archer', 'Lover', 7, 5, false),
('I Think He Knows', 'Lover', 7, 6, false),
('Miss Americana & the Heartbreak Prince', 'Lover', 7, 7, false),
('Paper Rings', 'Lover', 7, 8, false),
('Cornelia Street', 'Lover', 7, 9, false),
('Death by a Thousand Cuts', 'Lover', 7, 10, false),
('London Boy', 'Lover', 7, 11, false),
('Soon You''ll Get Better', 'Lover', 7, 12, false),
('False God', 'Lover', 7, 13, false),
('You Need to Calm Down', 'Lover', 7, 14, false),
('Afterglow', 'Lover', 7, 15, false),
('ME!', 'Lover', 7, 16, false),
('It''s Nice to Have a Friend', 'Lover', 7, 17, false),
('Daylight', 'Lover', 7, 18, false),

-- folklore - album_order 8
('the 1', 'folklore', 8, 1, false),
('cardigan', 'folklore', 8, 2, false),
('the last great american dynasty', 'folklore', 8, 3, false),
('exile', 'folklore', 8, 4, false),
('my tears ricochet', 'folklore', 8, 5, false),
('mirrorball', 'folklore', 8, 6, false),
('seven', 'folklore', 8, 7, false),
('august', 'folklore', 8, 8, false),
('this is me trying', 'folklore', 8, 9, false),
('illicit affairs', 'folklore', 8, 10, false),
('invisible string', 'folklore', 8, 11, false),
('mad woman', 'folklore', 8, 12, false),
('epiphany', 'folklore', 8, 13, false),
('betty', 'folklore', 8, 14, false),
('peace', 'folklore', 8, 15, false),
('hoax', 'folklore', 8, 16, false),
('the lakes', 'folklore', 8, 17, false),

-- evermore - album_order 9
('willow', 'evermore', 9, 1, false),
('champagne problems', 'evermore', 9, 2, false),
('gold rush', 'evermore', 9, 3, false),
('''tis the damn season', 'evermore', 9, 4, false),
('tolerate it', 'evermore', 9, 5, false),
('no body, no crime', 'evermore', 9, 6, false),
('happiness', 'evermore', 9, 7, false),
('dorothea', 'evermore', 9, 8, false),
('coney island', 'evermore', 9, 9, false),
('ivy', 'evermore', 9, 10, false),
('cowboy like me', 'evermore', 9, 11, false),
('long story short', 'evermore', 9, 12, false),
('marjorie', 'evermore', 9, 13, false),
('closure', 'evermore', 9, 14, false),
('evermore', 'evermore', 9, 15, false),
('right where you left me', 'evermore', 9, 16, false),
('it''s time to go', 'evermore', 9, 17, false),

-- Midnights - album_order 10
('Lavender Haze', 'Midnights', 10, 1, false),
('Maroon', 'Midnights', 10, 2, false),
('Anti-Hero', 'Midnights', 10, 3, false),
('Snow on the Beach', 'Midnights', 10, 4, false),
('You''re on Your Own, Kid', 'Midnights', 10, 5, false),
('Midnight Rain', 'Midnights', 10, 6, false),
('Question...?', 'Midnights', 10, 7, false),
('Vigilante Shit', 'Midnights', 10, 8, false),
('Bejeweled', 'Midnights', 10, 9, false),
('Labyrinth', 'Midnights', 10, 10, false),
('Karma', 'Midnights', 10, 11, false),
('Sweet Nothing', 'Midnights', 10, 12, false),
('Mastermind', 'Midnights', 10, 13, false),
('The Great War', 'Midnights', 10, 14, false),
('Bigger Than the Whole Sky', 'Midnights', 10, 15, false),
('Paris', 'Midnights', 10, 16, false),
('High Infidelity', 'Midnights', 10, 17, false),
('Glitch', 'Midnights', 10, 18, false),
('Would''ve, Could''ve, Should''ve', 'Midnights', 10, 19, false),
('Dear Reader', 'Midnights', 10, 20, false),
('Hits Different', 'Midnights', 10, 21, false),
('Snow on the Beach (feat. More Lana Del Rey)', 'Midnights', 10, 22, false),
('Karma (feat. Ice Spice)', 'Midnights', 10, 23, false),

-- The Tortured Poets Department - album_order 11
('Fortnight', 'The Tortured Poets Department', 11, 1, false),
('The Tortured Poets Department', 'The Tortured Poets Department', 11, 2, false),
('My Boy Only Breaks His Favorite Toys', 'The Tortured Poets Department', 11, 3, false),
('Down Bad', 'The Tortured Poets Department', 11, 4, false),
('So Long, London', 'The Tortured Poets Department', 11, 5, false),
('But Daddy I Love Him', 'The Tortured Poets Department', 11, 6, false),
('Fresh Out the Slammer', 'The Tortured Poets Department', 11, 7, false),
('Florida!!!', 'The Tortured Poets Department', 11, 8, false),
('Guilty as Sin?', 'The Tortured Poets Department', 11, 9, false),
('Who''s Afraid of Little Old Me?', 'The Tortured Poets Department', 11, 10, false),
('I Can Fix Him (No Really I Can)', 'The Tortured Poets Department', 11, 11, false),
('loml', 'The Tortured Poets Department', 11, 12, false),
('I Can Do It with a Broken Heart', 'The Tortured Poets Department', 11, 13, false),
('The Smallest Man Who Ever Lived', 'The Tortured Poets Department', 11, 14, false),
('The Alchemy', 'The Tortured Poets Department', 11, 15, false),
('Clara Bow', 'The Tortured Poets Department', 11, 16, false),
('The Black Dog', 'The Tortured Poets Department', 11, 17, false),
('imgonnagetyouback', 'The Tortured Poets Department', 11, 18, false),
('The Albatross', 'The Tortured Poets Department', 11, 19, false),
('Chloe or Sam or Sophia or Marcus', 'The Tortured Poets Department', 11, 20, false),
('How Did It End?', 'The Tortured Poets Department', 11, 21, false),
('So High School', 'The Tortured Poets Department', 11, 22, false),
('I Hate It Here', 'The Tortured Poets Department', 11, 23, false),
('thanK you aIMee', 'The Tortured Poets Department', 11, 24, false),
('I Look in People''s Windows', 'The Tortured Poets Department', 11, 25, false),
('The Prophecy', 'The Tortured Poets Department', 11, 26, false),
('Cassandra', 'The Tortured Poets Department', 11, 27, false),
('Peter', 'The Tortured Poets Department', 11, 28, false),
('The Bolter', 'The Tortured Poets Department', 11, 29, false),
('Robin', 'The Tortured Poets Department', 11, 30, false),
('The Manuscript', 'The Tortured Poets Department', 11, 31, false),

-- The Life of a Showgirl - album_order 12
('The Fate of Ophelia', 'The Life of a Showgirl', 12, 1, false),
('Elizabeth Taylor', 'The Life of a Showgirl', 12, 2, false),
('Opalite', 'The Life of a Showgirl', 12, 3, false),
('Father Figure', 'The Life of a Showgirl', 12, 4, false),
('Eldest Daughter', 'The Life of a Showgirl', 12, 5, false),
('Ruin The Friendship', 'The Life of a Showgirl', 12, 6, false),
('Actually Romantic', 'The Life of a Showgirl', 12, 7, false),
('Wi$h Li$t', 'The Life of a Showgirl', 12, 8, false),
('Wood', 'The Life of a Showgirl', 12, 9, false),
('CANCELLED!', 'The Life of a Showgirl', 12, 10, false),
('Honey', 'The Life of a Showgirl', 12, 11, false),
('The Life of a Showgirl', 'The Life of a Showgirl', 12, 12, false),

-- Non-Album (singles, features, soundtracks) - album_order 999
('Beautiful Eyes', 'Non-Album', 999, 1, false),
('Crazier', 'Non-Album', 999, 2, false),
('Two Is Better Than One', 'Non-Album', 999, 3, false),
('Hold On — Live', 'Non-Album', 999, 4, false),
('Safe & Sound', 'Non-Album', 999, 5, false),
('Eyes Open', 'Non-Album', 999, 6, false),
('Both of Us', 'Non-Album', 999, 7, false),
('Highway Don''t Care', 'Non-Album', 999, 8, false),
('Sweeter Than Fiction', 'Non-Album', 999, 9, false),
('I Don''t Wanna Live Forever', 'Non-Album', 999, 10, false),
('Macavity', 'Non-Album', 999, 11, false),
('Beautiful Ghosts', 'Non-Album', 999, 12, false),
('Christmas Tree Farm', 'Non-Album', 999, 13, false),
('Only The Young', 'Non-Album', 999, 14, false),
('Renegade', 'Non-Album', 999, 15, false),
('Birch', 'Non-Album', 999, 16, false),
('Gasoline', 'Non-Album', 999, 17, false),
('The Joker And The Queen', 'Non-Album', 999, 18, false),
('Carolina', 'Non-Album', 999, 19, false),
('All Of The Girls You Loved Before', 'Non-Album', 999, 20, false),
('You''re Losing Me (From The Vault)', 'Non-Album', 999, 21, true),
('The Alcott', 'Non-Album', 999, 22, false),
('us.', 'Non-Album', 999, 23, false);